# -
# *****************************************************************************
# Copyright 2026 Autodesk, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# *****************************************************************************
# +

import os
import unittest

from maya import cmds
from maya import standalone

test_dir = os.path.dirname(os.path.realpath(__file__))
resources_dir = os.path.join(test_dir, "..", "resources")


class MayaUsdDynamicFileFormatTestCase(unittest.TestCase):
    plugins_loaded = False

    @classmethod
    def setUpClass(cls):
        if not cls.plugins_loaded:
            standalone.initialize("MayaUsdDynamicFileFormatTest")
            cmds.loadPlugin("mayaUsdPlugin", quiet=True)
            cls.plugins_loaded = True

    @classmethod
    def tearDownClass(cls):
        standalone.uninitialize()

    def testLoadDynamicFileFormatPlugin(self):
        def createProxyShapeFromFile(filePath):
            usdNode = cmds.createNode(
                "mayaUsdProxyShape", skipSelect=True, name="UsdStageShape"
            )
            cmds.setAttr(usdNode + ".filePath", filePath, type="string")
            return usdNode

        def getStageFromProxyShape(shapeNode):
            from mayaUsd import lib as mayaUsdLib

            return mayaUsdLib.GetPrim(shapeNode).GetStage()

        usdFilePath = os.path.join(
            resources_dir, "DynamicFileFormat", "scatter_on_surface.usd"
        )
        proxyShape = createProxyShapeFromFile(usdFilePath)
        self.assertEqual(cmds.nodeType(proxyShape), "mayaUsdProxyShape")
        stage = getStageFromProxyShape(proxyShape)
        self.assertTrue(stage)

        # This prim should be there even if the BifrostDynamicFileFormat plugin is not loaded.
        rootPrim = stage.GetPrimAtPath("/Root")
        self.assertTrue(rootPrim)

        # This prim is generated by the BifrostDynamicFileFormat plugin.
        geoPrim = stage.GetPrimAtPath("/Root/geo")
        self.assertTrue(geoPrim)


if __name__ == "__main__":
    unittest.main(verbosity=2)
